[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[build.environment]
  MINIFLARE_DISABLE = "true"


[build.environment]
  NODE_OPTIONS = "--trace-warnings"
